### PR TITLE
1.3.2 dev

### PR DESCRIPTION
**Pull request by Yuer-QAQ**
## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Type of changes

- [x] Bug fix
- [x] New feature 
- [x] Enhancement
- [x] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by Kawaa-qwq** [comment]
wow，爆炸性功能

**Comment by NotArandomGUY** [comment]
XD

**Comment by Yuer-QAQ** [comment]
> 哇，爆炸性功能

都怪你 艹

**Comment by FeiFei-SS** [comment]
好厉害呀
That's awesome

**Comment by Yuer-QAQ** [comment]
> 好厉害呀 那真棒
有狗

**Comment by Kawaa-qwq** [comment]
这是一个令人热血沸腾的pr！

**Comment by tangtangebusi** [comment]
wow~fantastic

**Comment by kenadiss** [comment]
太厉害了

**Comment by Kawaa-qwq** [comment]
史诗

**Comment by NotArandomGUY** [comment]
HuTaoGenshinImpactGIF

**Comment by kenadiss** [comment]
666

**Pull request closed without merging**
