### PR TITLE
[closed until later] Fix Dvalin battle

### PR DESCRIPTION
**Pull request by thecutefinder**
See https://github.com/Anime-Game-Servers/Grasscutter-Quests/pull/25.

This is entirely untested and there's a 99% chance it's broken, I'm just submitting it as a draft PR so that I don't forget about its existence. I will work on getting the original (pre-compilation) `.proto` files used here, testing the code, and fixing bugs later, but it's past midnight, so I don't have the time for that.

Edits by maintainers are allowed to fix any bugs.

## Description

Please carefully read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md) before making any pull requests.
And, **Do not make a pull request to merge into stable unless it is a hotfix. Use the development branch instead.**
## Issues fixed by this PR
https://github.com/Anime-Game-Servers/Grasscutter-Quests/pull/25

## Type of changes

- [x] Bug fix
- [x] New feature 
- [ ] Enhancement
- [ ] Documentation

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] My pull request is unique and no other pull requests have been opened for these changes
- [x] I have read the [Contributing note](https://github.com/Grasscutters/Grasscutter/blob/stable/CONTRIBUTING.md) and [Code of conduct](https://github.com/Grasscutters/Grasscutter/blob/development/CODE_OF_CONDUCT.md)
- [x] I am responsible for any copyright issues with my code if it occurs in the future.

### CODE REVIEW

**Comment by thecutefinder** [comment]
We'll likely need to change the added protos to these instead:
* https://github.com/NickTheHuy/3.5_protos/blob/main/deobfuscated/QuestTransmitRsp.proto
* https://github.com/NickTheHuy/3.5_protos/blob/main/deobfuscated/QuestTransmitReq.proto

**Comment by thecutefinder** [comment]
Need to update sorapointa references to the new protos

**Comment by NotThorny** [comment]
> We'll likely need to change the added protos to these instead:
> 
>     * https://github.com/NickTheHuy/3.5_protos/blob/main/deobfuscated/QuestTransmitRsp.proto
> 
>     * https://github.com/NickTheHuy/3.5_protos/blob/main/deobfuscated/QuestTransmitReq.proto

The repository currently uses 3.4 protos, using 3.5 ones for this only means that it will be unusable. Would be a good idea to use 3.4 protos until the time comes when the repo is updated to 3.5.

**Comment by thecutefinder** [comment]
Ah, I see. I'll downgrade it to 3.4 protos in a minute once I have the chance.

**Comment by thecutefinder** [comment]
It builds successfully now, though I still need to check for bugs, as explained in the commit description.

**Comment by thecutefinder** [comment]
Still needs to be tested

**Comment by thecutefinder** [comment]
I don't have a 3.4 client, need to figure out how to download it later, I'm tired

**Comment by thecutefinder** [comment]
Closing temporarily so that I can PR 3.5, GitHub desktop is refusing to cooperate with me when opening multiple pull requests and I don't have the energy to figure it out

**Comment by thecutefinder** [comment]
Currently causing `Class cannot be created (missing no-arg constructor): sun.reflect.generics.reflectiveObjects.TypeVariableImpl` errors to be spammed in the console for 1-2 minutes before the server starts.

**Comment by thecutefinder** [comment]
Closing because this likely won't work without the rest of the questing fork.

**Pull request closed without merging**
